/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTryOnRouteImport } from './routes/api/try-on'
import { Route as ApiTurnaroundRouteImport } from './routes/api/turnaround'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTryOnRoute = ApiTryOnRouteImport.update({
  id: '/api/try-on',
  path: '/api/try-on',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTurnaroundRoute = ApiTurnaroundRouteImport.update({
  id: '/api/turnaround',
  path: '/api/turnaround',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/try-on': typeof ApiTryOnRoute
  '/api/turnaround': typeof ApiTurnaroundRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/try-on': typeof ApiTryOnRoute
  '/api/turnaround': typeof ApiTurnaroundRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/try-on': typeof ApiTryOnRoute
  '/api/turnaround': typeof ApiTurnaroundRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/try-on' | '/api/turnaround'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/try-on' | '/api/turnaround'
  id: '__root__' | '/' | '/api/try-on' | '/api/turnaround'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiTryOnRoute: typeof ApiTryOnRoute
  ApiTurnaroundRoute: typeof ApiTurnaroundRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/try-on': {
      id: '/api/try-on'
      path: '/api/try-on'
      fullPath: '/api/try-on'
      preLoaderRoute: typeof ApiTryOnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/turnaround': {
      id: '/api/turnaround'
      path: '/api/turnaround'
      fullPath: '/api/turnaround'
      preLoaderRoute: typeof ApiTurnaroundRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiTryOnRoute: ApiTryOnRoute,
  ApiTurnaroundRoute: ApiTurnaroundRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
